@baseUrl = http://localhost:3000/api

### Login
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "abc123",
  "password": "123456"
}

### luu token vao bien
@authToken = {{loginRequest.response.body.$.data.token}}

### Tao booking moi
# @name createBooking
POST {{baseUrl}}/v1/bookings
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "showtimeId": "69458be61231ce4578f2980b",
  "seats": [
    { "row": "A", "number": 1 },
    { "row": "A", "number": 2 }
  ]
}

### Luu bookingId tu response
@bookingId = {{createBooking.response.body.$.data._id}}

### Lay danh sach ve cua user dang login
GET {{baseUrl}}/v1/bookings
Authorization: Bearer {{authToken}}

### Lay chi tiet 1 ve cua user
GET {{baseUrl}}/v1/bookings/
Authorization: Bearer {{authToken}}