@baseUrl = http://localhost:3000/api/v1
@baseLogin = http://localhost:3000/api

### Login
# @name loginRequest
POST {{baseLogin}}/auth/login
Content-Type: application/json

{
  // tai khoan admin
  "username": "taolaadmin",
  "password": "admin123"
}

### luu token vao bien
@authToken = {{loginRequest.response.body.$.data.token}}

### get cinema
# @name getCinema
GET {{baseUrl}}/cinemas
Content-Type: application/json

### create cinema
# @name createCinema
POST {{baseUrl}}/cinemas
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Cinemax HCMUS",
    "address": "Trường Đại học Khoa học Tự nhiên, Đại học Quốc gia TP.HCM",
    "status": "open",
    "type": "imax",
    "rows": 7,
    "columns": 8
}