@baseUrl = http://localhost:3000/api/v1
@baseLogin = http://localhost:3000/api

### Login
# @name loginRequest
POST {{baseLogin}}/auth/login
Content-Type: application/json

{
  // tai khoan admin
  "username": "",
  "password": ""
}

### luu token vao bien
@authToken = {{loginRequest.response.body.$.data.token}}

### get cinema
# @name getCinema
GET {{baseUrl}}/cinemas
Content-Type: application/json

### create cinema
# @name createCinema
POST {{baseUrl}}/cinemas
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Cinemax Sinh Viên",
    "address": "Nhà Văn Hóa Sinh Viên, Đông Hoà, Dĩ An, Bình Dương",
    "seatLayout": [
        {
            "row": "A",
            "seats": ["A1", "A2", "A3", "A4", "A5"]
        },
        {
            "row": "B",
            "seats": ["B1", "B2", "B3", "B4", "B5"]
        },
        {
            "row": "C",
            "seats": ["C1", "C2", "C3", "C4", "C5"]
        },
        {
            "row": "D",
            "seats": ["D1", "D2", "D3", "D4", "D5"]
        },
        {
            "row": "E",
            "seats": ["E1", "E2", "E3", "E4", "E5"]
        }
    ]
}

### create cinema
# @name createCinema2
POST {{baseUrl}}/cinemas
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Cinemax Thủ Đức",
    "address": "216 Đ. Võ Văn Ngân, Bình Thọ, Thủ Đức, Thành phố Hồ Chí Minh",
    "seatLayout": [
        {
            "row": "A",
            "seats": ["A1", "A2", "A3", "A4", "A5", "A6"]
        },
        {
            "row": "B",
            "seats": ["B1", "B2", "B3", "B4", "B5", "B6"]
        },
        {
            "row": "C",
            "seats": ["C1", "C2", "C3", "C4", "C5", "C6"]
        },
        {
            "row": "D",
            "seats": ["D1", "D2", "D3", "D4", "D5", "D6"]
        },
        {
            "row": "E",
            "seats": ["E1", "E2", "E3", "E4", "E5", "E6"]
        }
    ]
}