@baseUrl = http://localhost:3000/api/v1
@baseLogin = http://localhost:3000/api

### Login
# @name loginRequest
POST {{baseLogin}}/auth/login
Content-Type: application/json

{
  // tai khoan admin
  "username": "taolaadmin",
  "password": "admin123"
}

### luu token vao bien
@authToken = {{loginRequest.response.body.$.data.token}}

### get cinema
# @name getCinema
GET {{baseUrl}}/cinemas
Content-Type: application/json

### create cinema
# @name createCinema
POST {{baseUrl}}/cinemas
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Cinemax Quận 1",
    "address": "Quận 1, Thành phố Hồ Chí Minh",
    "rows": 5,
    "columns": 5
}