@baseUrl = http://localhost:3000/api

### Register
# @name registerRequest
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
    "username": "anhcuongday",
    "email": "anhcuongday123@gmail.com",
    "password": "anhcuongday"
}

### Login
# @name loginRequest
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{
    "username": "anhcuongday",
    "password": "anhcuongday"
}

### Refresh Token
# @name refreshRequest
POST {{baseUrl}}/v1/auth/refresh
Content-Type: application/json

{
    "refreshToken": "<refresh_token_from_login>"
}